### ISSUE TITLE
mac下无效

### ISSUE THREAD

**Issue by maboloshi** [LookRain/streaming-pip#1]
Google Chrome 已是最新版本
版本 72.0.3626.28（正式版本）beta （64 位）

Mac 10.14.3 Beta (18D32a)
<img width="737" alt="2019-01-09 10 53 06" src="https://user-images.githubusercontent.com/7850715/50907143-9d014480-1461-11e9-9fab-7b7395f27a0b.png">

**Comment by LookRain** [comment]
hmmm 这是在youtube上吗？在其他视频网站上能正常使用吗？

**Comment by maboloshi** [comment]
恩 其他视频网站也无效

**Comment by LookRain** [comment]
> 恩 其他视频网站也无效

那估计是最新版canary对这个api做了改动，等会有时间了update下看看。谢谢report

**Comment by maboloshi** [comment]
已解决
> **Enable Picture-in-Picture**
Before we get into the code, let’s first make sure that we can view our results on the browser properly by enabling the required Chrome browser flags. Go to chrome://flags on your Chrome browser and enable the following:
> 
>-  Experimental Web Platform features
>- Enable Picture-in-Picture
>- Enable the use of SurfaceLayer objects for videos
